name: "Hello World Kamal"

on:
  push:
    branches:
      - main
      - master

jobs:
  hello-word:
  runs-on: ubuntu-latest
  steps:
    - name: Hello World
      run: echo "Hello World from Kamal"
